# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
data_url: ""
train_url: ""
checkpoint_url: ""
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"
checkpoint_path: './checkpoint/'
checkpoint_file: './checkpoint/'
device_target: Ascend
enable_profiling: False

pre_trained: "/cache/data"
coco_root: "./COCO"
ckpt_path: './'
ann_file: "./COCO/annotations/instances_train2017s.json"
# ==============================================================================
modelarts_dataset_unzip_name: 'cocodataset'
need_modelarts_dataset_unzip: True

img_path: ''
result_path: ''

# Training options
num_parallel_workers: 1
python_multiprocessing: 
img_width: 1280
img_height: 768
keep_ratio: True
flip_ratio: 0.5
expand_ratio: 1.0

max_instance_count: 128
mask_shape: [28, 28]

# LR
base_lr: 0.02
base_step: 58633
total_epoch: 13
warmup_step: 500
warmup_ratio: 0.333333
sgd_momentum: 0.9

# train
batch_size: 1
loss_scale: 1
momentum: 0.91
weight_decay: 0.0001 # 1e-4
pretrain_epoch_size: 0
epoch_size: 12
save_checkpoint: True
save_checkpoint_epochs: 1
keep_checkpoint_max: 12
save_checkpoint_path: "./"

mindrecord_dir: "./MindRecord_COCO"
train_data_type: "train2017"
val_data_type: "val2017"
instance_set: "annotations/instances_{}.json"
coco_classes: ['background', 'person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus',
                     'train', 'truck', 'boat', 'traffic light', 'fire hydrant',
                     'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog',
                     'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra',
                     'giraffe', 'backpack', 'umbrella', 'handbag', 'tie',
                     'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball',
                     'kite', 'baseball bat', 'baseball glove', 'skateboard',
                     'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup',
                     'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple',
                     'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza',
                     'donut', 'cake', 'chair', 'couch', 'potted plant', 'bed',
                     'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote',
                     'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink',
                     'refrigerator', 'book', 'clock', 'vase', 'scissors',
                     'teddy bear', 'hair drier', 'toothbrush']
num_classes: 81

only_create_dataset: False
run_distribute: False
do_train: True
do_eval: False
dataset: "coco"
device_id: 0
device_num: 1
rank_id: 0

# queryinst export
file_name: "queryinst"
file_format: "MINDIR"
ckpt_file: '/'
ckpt_file_local: './'
export_input_type: float16

# other
learning_rate: 0.002
buffer_size: 1000
save_checkpoint_steps: 1000
sink_size: -1
dataset_sink_mode: True
lr: 0.01

# Model Description
model_name: queryinst

---
# Config description for each option
enable_modelarts: 'Whether training on modelarts, default: False'
data_url: 'Dataset url for obs'
train_url: 'Training output url for obs'
data_path: 'Dataset path for local'
output_path: 'Training output path for local'
ann_file: 'Ann file, default is val.json.'

device_target: 'Target device type'
enable_profiling: 'Whether enable profiling while training, default: False'
only_create_dataset: 'If set it true, only create Mindrecord, default is false.'
run_distribute: 'Run distribute, default is false.'
do_train: 'Do train or not, default is true.'
do_eval: 'Do eval or not, default is false.'
dataset: 'Dataset, default is coco.'
pre_trained: 'Pretrain file path.'
device_id: 'Device id, default is 0.'
device_num: 'Use device nums, default is 1.'
rank_id: 'Rank id, default is 0.'
file_format: 'file format'
img_path: "image file path."
result_path: "result file path."

---
device_target: ['Ascend', 'GPU', 'CPU']
file_format: ["AIR", "ONNX", "MINDIR"]
export_input_type: ["float16", "float32"]
